/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cartoonizer.rag.openai;

import com.cartoonizer.rag.shared.utils.ApiKeys;
import com.cartoonizer.rag.shared.utils.ModelNames;
import com.cartoonizer.rag.shared.utils.Utils;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.SwingUtilities;

/**
 *
 * @author cagi
 */
public class OpenAiChatApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OpenAiChatApp.class.getName());

    /**
     * Creates new form OpenAiChatApp
     */
    public OpenAiChatApp() {
        initComponents();
    }
    private OpenAiChat chat;
    private String savedViewClass;
    private String savedViewModel;
    private String dialogXml;
    private String dialogClass;
    private void initOpenAi() {
        String documentsPath = Paths.get("./example-files").toAbsolutePath().normalize().toString();

        String fileToGenerate = "HomeFragment";
        String answerPath = Paths.get("./output-files").toAbsolutePath().normalize().toString() + "/" + fileToGenerate + ".txt";
        String processedAnswerPath = Paths.get("./processed-files/processed-").toAbsolutePath().normalize().toString() + fileToGenerate + ".txt";
        
        String pathForViewClass = documentsPath  + "/" + fileToGenerate + ".kt";
        String pathViewModel = documentsPath  + "/HomeViewModel.kt";
        String pathLayout = documentsPath  + "/fragment_home.xml";
        String pathSharedViewModel = documentsPath  + "/MainActivityViewModel.kt";
        System.out.println("pathViewModel " + pathViewModel);
        System.out.println("pathForViewClass " + pathForViewClass);
        
        dialogXml = Utils.readFullFile(documentsPath  + "/custom_dialog.xml");
        dialogClass = Utils.readFullFile(documentsPath  + "/CustomDialog.kt");
        savedViewClass = Utils.readFullFile(pathForViewClass);
        savedViewModel = Utils.readFullFile(pathViewModel);
        String savedLayout = Utils.readFullFile(pathLayout);
        String savedSharedViewModel = Utils.readFullFile(pathSharedViewModel);
        
        File f = new File(documentsPath);
        if (f.exists()) {
            prepareQuestion();
            chat = new OpenAiChat(ApiKeys.OPENAI_API_KEY, ModelNames.CHAT_GPT_MINI, documentsPath, answerPath, processedAnswerPath);
        }
        
    }
    public void setupOpenAi() {
        prepareQuestion();
        btnStart.setEnabled(false);
        btnAskQuestion.setEnabled(false);
        new Thread(){
            @Override
            public void run() {
                initOpenAi();
                chat.setup();
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        btnAskQuestion.setEnabled(true);
                    }
                });
            }
            
        }.start();
    }
    public void prepareQuestion() {
        String question = 
            "1. provide a jetpack Compose composable that implements the following jetpack views class class \n" +
            savedViewClass +
            "2. provide a Compose viewModel to be used by the composable based on the following Jetpack Views viewModel, exposing a Compose-friendly `UiState + UiEvent` architecture \n" +
            savedViewModel +
            "3. When implementing the composable and viewModel preserve Jetpack Views navigation  \n" +
            "4. Use dialog state, lifecycle collection of state/events for dialog handling \n" +
            "5. Use state holders/data classes to fully replace the fragment button logic. \n" +
            "6. Provide a compose CustomDialog implementation based on this custom dialog xml file" +
            dialogXml +
            "and this dialog " +
            dialogClass +
            "\nUse only android and jetpack compose references";
        textAreaQuestion.setText(question);
    }
    public void ask() {
        textAreaAnswer.setText("");
        btnAskQuestion.setEnabled(false);
        new Thread(){
            @Override
            public void run() {
                String answer = chat.askQuestion(textAreaQuestion.getText(), 3, 0.7);
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        textAreaAnswer.setText(answer);
                        btnAskQuestion.setEnabled(false);
                    }
                });
            }
            
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAnswer = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaQuestion = new javax.swing.JTextArea();
        btnStart = new javax.swing.JButton();
        btnAskQuestion = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Answer");

        textAreaAnswer.setColumns(20);
        textAreaAnswer.setRows(5);
        jScrollPane1.setViewportView(textAreaAnswer);

        jLabel2.setText("Enter the question");

        textAreaQuestion.setColumns(20);
        textAreaQuestion.setRows(5);
        jScrollPane2.setViewportView(textAreaQuestion);

        btnStart.setText("Start session");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnAskQuestion.setText("Ask question");
        btnAskQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askQuestion(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAskQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(701, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnAskQuestion)
                    .addComponent(btnExit))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2)
                    .addContainerGap(638, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        setupOpenAi();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnExitActionPerformed

    private void askQuestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askQuestion
        ask();
    }//GEN-LAST:event_askQuestion

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OpenAiChatApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAskQuestion;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaAnswer;
    private javax.swing.JTextArea textAreaQuestion;
    // End of variables declaration//GEN-END:variables
}
